version: "3"

volumes:
  vizier-data:

services:
  vizier:
    image: vizier-desktop:latest
    build: .
    ports:
      - "127.0.0.1:5000:5000"
      - "127.0.0.1:8089:8089"
    volumes:
      - "vizier-data:/data"
    deploy:
      resources:
        reservations:
          memory: 2GB
